name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "unbound"
logpush = true
kv_namespaces = [
  { binding = "kv", id = "5f7cdd115f374b4ab80fbf879416eee0" }
]
[placement]
mode = "smart"

[triggers]
crons = [ ]
